<?php
/**
 * @copyright 2020 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE
 * @param array $this->entries
 */
declare (strict_types=1);
?>
<section>
    <header><h1>Operations</h1></header>
    <table>
        <colgroup>
            <col class="time" />
            <col class="data" span="46" />
        </colgroup>
        <thead>
            <tr><th             >Time</th>
                <th colspan="41">Analytical Data</th>
                <th colspan= "2"></th>
                <th colspan= "2">Finish</th>
                <th             >Comments</th>
            </tr>
            <tr><th>Time</th>
                <th colspan= "3">Weather</th>
                <th colspan= "4">Turbidity</th>
                <th colspan="12">Chlorine</th>
                <th colspan= "6">pH</th>
                <th colspan= "6">Temperature</th>
                <th             >Fluoride</th>
                <th colspan= "2">Hardness</th>
                <th colspan= "2">Alkalinity</th>
                <th colspan= "2">Odor</th>
                <th colspan= "2">Chloride</th>
                <th             >Stability Index</th>
                <th colspan= "3">UV 254</th>
                <th             >Bench NTU</th>
                <th             >Comments</th>
            </tr>
            <tr><th rowspan="2">Time</th>
                <th rowspan="2">Temperature</th>
                <th rowspan="2">Conditions</th>

                <!-- Turbidity -->
                <th rowspan="2">Precipitation</th>
                <th rowspan="2">Raw</th>
                <th rowspan="2">Basin</th>
                <th rowspan="2">Filter</th>
                <th rowspan="2">Finish</th>

                <!-- Chlorine -->
                <th colspan="2">Basin</th>
                <th colspan="2">Prelift</th>
                <th colspan="2">Filter</th>
                <th colspan="2">B Filter</th>
                <th colspan="2">Clrwll</th>
                <th colspan="2">Finish</th>

                <!-- pH -->
                <th rowspan="2">Raw</th>
                <th rowspan="2">Basin</th>
                <th rowspan="2">Filter</th>
                <th rowspan="2">B Filter</th>
                <th rowspan="2">Clrwll</th>
                <th rowspan="2">Finish</th>

                <!-- Temperature -->
                <th rowspan="2">Raw</th>
                <th rowspan="2">Basin</th>
                <th rowspan="2">Filter</th>
                <th rowspan="2">B Filter</th>
                <th rowspan="2">Clrwll</th>
                <th rowspan="2">Finish</th>

                <th rowspan="2">Finish</th>

                <th rowspan="2">Raw</th>
                <th rowspan="2">Finish</th>
                <th rowspan="2">Raw</th>
                <th rowspan="2">Finish</th>
                <th rowspan="2">Raw</th>
                <th rowspan="2">Finish</th>
                <th rowspan="2">Raw</th>
                <th rowspan="2">Finish</th>

                <th>Raw Index</th>
                <th>Box Index</th>
                <th>Finish Index</th>

            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</section>
